### ISSUE TITLE
Issue with fromJSON method and byte arrays

### ISSUE THREAD

**Issue by drogars** [Aviacode/nTsMapper#6]
The TypeScript code produced from a C# class that contains a byte[], assume that byte is an object and tries to apply the .map to it.

c# property
`public byte[] Picture { get; set; }`

This is the code that was produced in TypeScript:
`picture: json.picture === null ? null : json.picture.map(o => o)`
and this is the code I changed it to, to make it work:
`picture: json.picture`

Hopefully, this is helpful.

**Comment by drogars** [comment]
Sorry, this is not entirely correct.  The byte array is getting serialized by JSON into a string, but nTsMapper thinks it's a collection and so tries to use the `.map` function on the collection.  Not sure if this should be handled by configuring the JSON serializer or making a change to nTsMapper.  Thoughts?

**Comment by drogars** [comment]
I investigated changing the way JSON.net serializes byte arrays, but I didn't feel comfortable writing my own serializer.   I was able to "fix" this by adding the following custom mapping:

```
new TypeMapping
{
    MatchesType = tr => typeof(byte[]) == tr,
    DestinationType = "string",
    DestinationAssignmentTemplate = "{0}"
}
```

However, this requires me to modify nTsMapper directly.  I would be happy to make a pull request for this "fix" if this is how you want it to work.  I suspect we need to implement a way for the consumers of nTsMapper to provide their own custom TypeMappings or possibly move away from the external exe and include the T4 template directly in the consumer's project.  Thoughts?

**Comment by mike-schenk** [comment]
Yes, there does need to be a way for consumers to provider their own custom TypeMappings. This will require a bit of a redesign.

In the meantime, changing the default mapping for C# by[] to be a TypeScript string instead of a number[] is a pretty good workaround. We actually ran into this exact problem the other day. I would expect all of the .Net JSON serializers to encode the byte[] in base64 by default. Certainly, that's what the default one in WebAPI is doing.

We'd happily accept a pull request as you described.

**Comment by drogars** [comment]
I will work on that PR as soon as I have some time.

**Comment by mike-schenk** [comment]
Pull request #7 has been merged.
